version: '3'
services:
  openvpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - ./openvpn:/etc/openvpn
    environment:
      - EASYRSA_KEY_SIZE=4096
      - EASYRSA_REQ_CN=MyVPN
      - EASYRSA_BATCH=1
    ports:
      - "1194:1194/udp"
    dns:
      - 1.1.1.1
      - 8.8.8.8
